import RPi.GPIO as GPIO
import time
import datetime
from random import randint
import sc2
import socket
import subprocess
sc2.init()

s = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
print("Socket Created")

host = '10.1.1.10'
port = 12345
time.sleep(3)
s.connect((host,port))

i = 0
mode = 2

playing = 0 
while True:
    """
        data = conn.recv(1024)
        if data:
        print("Receive Data: %s" % str(data.decode('utf-8')))
        else:
        break
        i += 1
        i %= 4
        sc2.reset(i+1,1)
        time.sleep(0.3)
        """
    if mode == 0:
        sc2.showTime()
        data = conn.recv(1024)
        if data:
            print("Receive Data: %s" % str(data.decode('utf-8')))
            mode=mode+1
    elif mode ==1:
        sc2.countDown()
        mode=mode+1
    elif mode ==2:
        data = "Hi"
        if playing == 0:
            player = subprocess.Popen(["omxplayer", "House.mp3", "-ss", "0"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            playing = 1
        time.sleep(217)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(125)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(342)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1148)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(684)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(5234)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(2186)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(4711)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1873)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1398)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1366)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(959)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1784)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(940)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(938)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1373)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(459)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(960)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(946)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(307)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(2433)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(900)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1609)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(262)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(937)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(910)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(2168)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(590)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(896)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1899)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(906)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(888)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(2739)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(948)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(344)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1511)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(939)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(912)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(343)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(2395)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(935)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1380)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1405)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(938)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(2747)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(930)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1612)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(228)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(934)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(936)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(2206)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(524)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(944)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1618)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1155)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(935)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1839)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(903)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(930)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1617)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1158)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(942)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(2191)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(536)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(934)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(359)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1261)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(250)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(321)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(586)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(942)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(2730)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(936)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(1879)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(921)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(906)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(937)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(942)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(930)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(875)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(3722)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(989)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(377)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(14302)
        s.sendall(data.encode('utf-8'))
        sc2.resetlight(randint(11,19),1)
        time.sleep(2071)
        data = "end"
        s.sendall(data.encode('utf-8'))
        mode = 0

conn.close()
